const state = { catalog: [], filtered: [], selected: null, category: 'All', query: '', regex: false, flags: 'i', selectedIds: new Set(), renderLimit: 120, favorites: new Set(JSON.parse(localStorage.getItem('dim-sum-favorites') || '[]')), history: JSON.parse(localStorage.getItem('dim-sum-history') || '[]') };
const $ = (id) => document.getElementById(id);
const lore = (dish) => ({ origin: `A fictional tea-house note imagines ${dish.name.en} taking shape in a bustling Kowloon kitchen where the first basket was counted by the rhythm of the kettle.`, facts: [`Fictional catalog fact: its best-known table companion is a cup of fragrant tea.`, `Fictional catalog fact: the name is said to be easiest to remember after the first bite.`, `Fictional catalog fact: cooks traditionally watch the steam, not the clock.`] });
function imageUrl(dish) { return dish.image?.assetUrl || ''; }
async function hydrateImage(image, dish) { if (!image || image.src || !dish.image?.releaseUrl) return; try { image.src = await window.atlas.ensureImage({ releaseUrl: dish.image.releaseUrl, relativePath: dish.image.path }); } catch { image.classList.add('image-unavailable'); image.alt = `${dish.name.en}, image unavailable in the catalog release`; } }
function dishText(d) { return [d.name?.en, d.name?.zhHant, d.description?.en, d.description?.yue, d.category, d.subcategory, ...(d.ingredients || []), ...(d.allergens || [])].join(' ').toLowerCase(); }
function renderChips() { const categories = ['All', ...new Set(state.catalog.map(d => d.category).filter(Boolean))].slice(0, 9); $('category-chips').innerHTML = categories.map(c => `<button class="chip ${c === state.category ? 'active' : ''}" data-category="${c}">${c.replaceAll('-', ' ')}</button>`).join(''); document.querySelectorAll('[data-category]').forEach(b => b.onclick = () => { state.category = b.dataset.category; apply(); }); }
function matches(d) { if (!state.query) return true; const text = dishText(d); if (!state.regex) return text.includes(state.query.toLowerCase()); try { return new RegExp(state.query, state.flags).test(text); } catch { return false; } }
function apply() { state.filtered = state.catalog.filter(d => (state.category === 'All' || d.category === state.category) && matches(d)); renderGallery($('gallery'), state.filtered); $('dish-count').textContent = state.catalog.length.toLocaleString(); $('hero-total').textContent = state.catalog.length.toLocaleString(); $('favorite-count').textContent = state.favorites.size; }
function renderGallery(target, dishes) { const visible = dishes.slice(0, state.renderLimit); target.innerHTML = visible.map(d => `<button class="card" data-id="${d.id}"><img loading="lazy" src="${imageUrl(d)}" alt="${d.image?.alt?.en || d.name.en}" /><div class="card-copy"><h3>${d.name.en}</h3><p>${d.name.zhHant || ''}</p><div class="card-meta"><span>${(d.category || 'dish').replaceAll('-', ' ')}</span><span>${state.selectedIds.has(d.id) ? '✓ Selected' : state.favorites.has(d.id) ? '♥' : '♡'}</span></div></div></button>`).join('') || '<p class="hero-copy">No dishes match this search.</p>'; if (visible.length < dishes.length) { const more = document.createElement('button'); more.className = 'filter-button load-more'; more.textContent = `Load more (${dishes.length - visible.length} remaining)`; more.onclick = () => { state.renderLimit += 120; renderGallery(target, dishes); }; target.append(more); } target.querySelectorAll('[data-id]').forEach(b => { const dish = state.catalog.find(d => d.id === b.dataset.id); hydrateImage(b.querySelector('img'), dish); b.onclick = (event) => { if (event.shiftKey || event.ctrlKey) { toggleSelection(b.dataset.id); } else select(b.dataset.id); }; }); }
function toggleSelection(id) { state.selectedIds.has(id) ? state.selectedIds.delete(id) : state.selectedIds.add(id); $('selection-count').textContent = state.selectedIds.size; apply(); }
async function exportSelected() { const records = state.catalog.filter(d => state.selectedIds.has(d.id)); if (!records.length) return toast('Select at least one image first.'); const imagesOnly = confirm('Export the selected local images and a manifest? Choose Cancel for metadata only.'); const format = imagesOnly ? 'json' : prompt('Format: json, csv, markdown, txt, or html', 'json'); if (!['json','csv','markdown','txt','html'].includes(format)) return toast('Choose a supported export format.'); const archive = prompt('Archive: blank, zip, or 7z', '7z'); const password = archive === '7z' ? prompt('Optional 7z password, leave blank for none', '') : ''; try { const result = await window.atlas.exportRecords({ records, format, archive: archive || null, password, imagesOnly }); if (!result.canceled) toast(`Exported ${records.length} selected images to ${result.archive || result.format}.`); } catch (error) { toast(error.message); } }
function select(id) { const d = state.catalog.find(x => x.id === id); if (!d) return; state.selected = d; const fiction = lore(d); $('detail').innerHTML = `<img src="${imageUrl(d)}" alt="${d.image?.alt?.en || d.name.en}" /><div class="detail-body"><p class="eyebrow">${(d.category || 'dish').replaceAll('-', ' ')}</p><h2>${d.name.en}</h2><p class="subtitle">${d.name.zhHant || ''} · ${d.jyutping || ''}</p><p>${d.description?.en || 'A catalogued dim-sum dish with a story waiting to be tasted.'}</p><p class="detail-label">Fictional origin lore</p><p>${fiction.origin}</p><p class="detail-label">Fictional catalog facts</p><ul>${fiction.facts.map(f => `<li>${f}</li>`).join('')}</ul><p class="detail-label">Ingredients</p><div class="tag-row">${(d.ingredients || []).map(x => `<span class="tag">${x}</span>`).join('')}</div><p class="detail-label">Allergens</p><div class="tag-row">${(d.allergens || []).map(x => `<span class="tag">${x}</span>`).join('') || '<span class="tag">None listed</span>'}</div><button class="filter-button" style="margin-top:22px" id="favorite-detail">${state.favorites.has(d.id) ? '♥ Saved' : '♡ Save dish'}</button></div>`; $('favorite-detail').onclick = () => toggleFavorite(d.id); }
function toggleFavorite(id) { state.favorites.has(id) ? state.favorites.delete(id) : state.favorites.add(id); localStorage.setItem('dim-sum-favorites', JSON.stringify([...state.favorites])); recordHistory('favorite', state.favorites.has(id) ? 'Saved a dish' : 'Removed a dish'); apply(); if (state.selected?.id === id) select(id); }
function recordHistory(action, message) { state.history.unshift({ at: new Date().toISOString(), action, message }); state.history = state.history.slice(0, 200); localStorage.setItem('dim-sum-history', JSON.stringify(state.history)); if (!$('history-panel').classList.contains('hidden')) renderHistory(); }
function renderHistory() { const q = ($('history-search')?.value || '').toLowerCase(); const from = $('history-from')?.value || ''; const to = $('history-to')?.value || ''; const rows = state.history.filter(x => (!q || `${x.action} ${x.message}`.toLowerCase().includes(q)) && (!from || x.at.slice(0,10) >= from) && (!to || x.at.slice(0,10) <= to)); $('history-list').innerHTML = rows.map(x => `<article class="history-entry"><time>${new Date(x.at).toLocaleString()}</time><strong>${x.action}</strong><span>${x.message}</span></article>`).join('') || '<p>No history matches these filters.</p>'; }
function bindTabs() { const tabs = [...document.querySelectorAll('.tab')]; tabs.forEach((t, i) => { t.setAttribute('tabindex', i === 0 ? '0' : '-1'); t.setAttribute('aria-controls', `${t.dataset.tab}-panel`); t.onclick = () => { document.querySelectorAll('.tab').forEach(x => { x.classList.remove('active'); x.setAttribute('aria-selected', 'false'); x.setAttribute('tabindex', '-1'); }); t.classList.add('active'); t.setAttribute('aria-selected', 'true'); t.setAttribute('tabindex', '0'); document.querySelectorAll('.panel').forEach(p => p.classList.add('hidden')); $(`${t.dataset.tab}-panel`).classList.remove('hidden'); if (t.dataset.tab === 'favorites') renderGallery($('favorites-gallery'), state.catalog.filter(d => state.favorites.has(d.id))); if (t.dataset.tab === 'history') renderHistory(); }; t.onkeydown = e => { if (!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)) return; e.preventDefault(); const i = e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : (tabs.indexOf(t) + (e.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; tabs[i].focus(); tabs[i].click(); }; }); const nav = document.querySelector('.tabs'); if (nav && !nav.querySelector('.electron-tab-search')) { const tools = document.createElement('div'); tools.className = 'electron-tab-search'; tools.innerHTML = '<input id="electron-tab-search" type="search" placeholder="Find tabs" aria-label="Find tabs"><button id="electron-tab-more" type="button">More</button><div id="electron-tab-menu" class="hidden"></div>'; nav.append(tools); const render = () => { const q = $('electron-tab-search').value.toLowerCase(); const menu = $('electron-tab-menu'); const shown = tabs.filter(t => !q || t.textContent.toLowerCase().includes(q)); menu.innerHTML = shown.map(t => `<button type="button" data-tab-result="${t.dataset.tab}">${t.textContent.trim()}</button>`).join('') || '<span>No matching tabs.</span>'; menu.querySelectorAll('[data-tab-result]').forEach(b => b.onclick = () => tabs.find(t => t.dataset.tab === b.dataset.tabResult).click()); }; $('electron-tab-search').oninput = render; $('electron-tab-more').onclick = () => { render(); $('electron-tab-menu').classList.toggle('hidden'); }; } }
async function init() { const data = await window.atlas.readCatalog(); state.catalog = data.dishes || []; renderChips(); apply(); bindTabs(); $('search').oninput = e => { state.query = e.target.value; state.regex = false; apply(); }; $('regex-button').onclick = () => { $('regex-pattern').value = state.query; $('regex-flags').value = state.flags; $('regex-dialog').showModal(); }; $('apply-regex').onclick = event => { event.preventDefault(); const pattern = $('regex-pattern').value; const flags = $('regex-flags').value; try { new RegExp(pattern, flags); state.query = pattern; state.flags = flags; state.regex = true; $('search').value = pattern; $('regex-dialog').close(); apply(); toast(`Regex search enabled, ${state.filtered.length.toLocaleString()} matches.`); } catch (error) { $('regex-status').textContent = `Invalid regex: ${error.message}`; } }; $('settings-button').onclick = () => { $('theme').value = localStorage.getItem('dim-sum-theme') || 'light'; $('funny-level').value = localStorage.getItem('dim-sum-funny') || '3'; $('settings-dialog').showModal(); }; $('save-settings').onclick = event => { event.preventDefault(); const theme = $('theme').value; const level = Math.min(5, Math.max(1, Number($('funny-level').value) || 3)); localStorage.setItem('dim-sum-theme', theme); localStorage.setItem('dim-sum-funny', String(level)); document.documentElement.dataset.theme = theme; $('settings-dialog').close(); toast(`Settings saved: ${theme} theme, funny level ${level}.`); }; const savedTheme = localStorage.getItem('dim-sum-theme'); if (savedTheme) document.documentElement.dataset.theme = savedTheme; $('export-button').onclick = exportSelected; $('bulk-export').onclick = exportSelected; $('select-visible').onclick = () => { state.filtered.slice(0, 120).forEach(d => state.selectedIds.add(d.id)); $('selection-count').textContent = state.selectedIds.size; apply(); }; $('clear-selection').onclick = () => { state.selectedIds.clear(); $('selection-count').textContent = '0'; apply(); }; }
function toast(message) { $('toast').textContent = message; $('toast').classList.add('show'); narrate(message); setTimeout(() => $('toast').classList.remove('show'), 2800); }
function mountRegexGuide() { const dialog = $('regex-dialog'); if (!dialog || dialog.querySelector('.regex-guide')) return; const guide = document.createElement('section'); guide.className = 'regex-guide'; guide.innerHTML = `<h3>Regex character guide</h3><p>JavaScript regex runs locally. Plain text remains the default.</p><table><thead><tr><th>Character</th><th>Example</th><th>Meaning</th></tr></thead><tbody><tr><th>Literal</th><td><code>har gow</code></td><td>Matches exact text.</td></tr><tr><th>Class</th><td><code>[abc]</code></td><td>One character from a set. Use <code>[^abc]</code> to negate.</td></tr><tr><th>Range</th><td><code>[a-z]</code></td><td>One character in a range.</td></tr><tr><th>Wildcard</th><td><code>.</code></td><td>One character except a line terminator.</td></tr><tr><th>Anchors</th><td><code>^ $</code></td><td>Start and end of input.</td></tr><tr><th>Group</th><td><code>(har|siu mai)</code></td><td>Capture and combine expressions.</td></tr><tr><th>Quantifier</th><td><code>* + ? {2,4}</code></td><td>Repeat the previous token.</td></tr><tr><th>Escape</th><td><code>\.</code></td><td>Match punctuation literally.</td></tr><tr><th>Flags</th><td><code>g i m s u y</code></td><td>Global, case-insensitive, multiline, dotAll, Unicode, sticky.</td></tr></tbody></table><label>Sample text <textarea id="regex-sample" maxlength="2000" placeholder="Paste sample text"></textarea></label><p id="regex-inspector" role="status">Enter a pattern and sample to inspect matches.</p>`; dialog.querySelector('form').append(guide); const inspect = () => { const pattern = $('regex-pattern').value; const flags = $('regex-flags').value; const sample = $('regex-sample').value; try { const re = new RegExp(pattern, flags.includes('g') ? flags : `${flags}g`); const matches = [...sample.matchAll(re)]; $('regex-inspector').textContent = `${matches.length} match${matches.length === 1 ? '' : 'es'}${matches[0]?.groups ? `; named captures: ${Object.keys(matches[0].groups).join(', ') || 'none'}` : ''}`; } catch (error) { $('regex-inspector').textContent = `Invalid regex: ${error.message}`; } }; ['regex-pattern','regex-flags','regex-sample'].forEach(id => $(id)?.addEventListener('input', inspect)); }
mountRegexGuide();
function mountLanguageControls() { const form = $('settings-dialog')?.querySelector('form'); if (!form || form.querySelector('.language-controls')) return; const section = document.createElement('section'); section.className = 'language-controls'; section.innerHTML = `<h3>Language and voice</h3><label>Language mode <select id="language-mode"><option value="en">English</option><option value="yue">廣東話</option><option value="bilingual">Bilingual</option></select></label><label>English funny level <input id="funny-en" type="range" min="1" max="5" value="2"><output>2</output></label><label>Cantonese funny level <input id="funny-yue" type="range" min="1" max="5" value="2"><output>2</output></label><p>Funny levels change voice, never dish facts. Settings persist locally.</p>`; form.append(section); const saved = JSON.parse(localStorage.getItem('dim-sum-language-settings') || '{"language":"en","funnyEn":"2","funnyYue":"2"}'); const apply = () => { localStorage.setItem('dim-sum-language-settings', JSON.stringify(saved)); const mode = saved.language; const brand = document.querySelector('.brand small'); const hero = document.querySelector('.hero-copy'); if (brand && hero) { if (mode === 'yue') { brand.textContent = '港式點心畫廊'; hero.textContent = '瀏覽每款點心，睇清楚材料、過敏原，同埋標明係虛構嘅茶樓故事。'; } else if (mode === 'bilingual') { brand.textContent = 'Hong Kong tea-house catalogue · 港式點心目錄'; hero.textContent = 'Browse every dish with ingredients and fictional lore · 瀏覽每款點心，睇材料同虛構故事。'; } else { brand.textContent = 'Hong Kong tea-house catalogue'; hero.textContent = 'Browse every dish in the atlas, with ingredients, allergens, and a little fictional tea-house lore.'; } } }; const mode = $('language-mode'); const en = $('funny-en'); const yue = $('funny-yue'); mode.value = saved.language; en.value = saved.funnyEn; yue.value = saved.funnyYue; [mode,en,yue].forEach(field => field.addEventListener('input', () => { saved.language = mode.value; saved.funnyEn = en.value; saved.funnyYue = yue.value; field.parentElement.querySelector('output')?.replaceChildren(document.createTextNode(field.value)); apply(); })); apply(); }
function mountNarratorControls() { const form = $('settings-dialog')?.querySelector('form'); if (!form || form.querySelector('.narrator-controls')) return; const section = document.createElement('section'); section.className = 'narrator-controls'; section.innerHTML = '<h3>Optional narrator</h3><p>Off by default. Speech is serialized so announcements never overlap.</p><label><input id="narrator-enabled" type="checkbox"> Narrate app events</label><label>Voice language<select id="narrator-language"><option value="en">English</option><option value="yue">Cantonese</option><option value="both">Both</option></select></label>'; form.append(section); const saved = JSON.parse(localStorage.getItem('dim-sum-narrator') || '{}'); $('narrator-enabled').checked = saved.enabled === true; $('narrator-language').value = saved.language || 'en'; const save = () => localStorage.setItem('dim-sum-narrator', JSON.stringify({ enabled: $('narrator-enabled').checked, language: $('narrator-language').value })); $('narrator-enabled').onchange = save; $('narrator-language').onchange = save; }
function mountSettingsSearch() { const form = $('settings-dialog')?.querySelector('form'); if (!form || form.querySelector('.settings-search')) return; const wrap = document.createElement('label'); wrap.className = 'settings-search'; wrap.innerHTML = 'Find settings <span><input id="settings-search" type="search" placeholder="Search settings" aria-label="Search settings"><button id="settings-regex" type="button" aria-label="Build a regex for settings">.*</button></span>'; form.insertBefore(wrap, form.firstChild); const filter = () => { const q = ($('settings-search').value || '').toLowerCase(); form.querySelectorAll('label, .language-controls, .narrator-controls').forEach(node => { if (node === wrap) return; node.hidden = Boolean(q) && !node.textContent.toLowerCase().includes(q); }); }; $('settings-search').oninput = filter; $('settings-regex').onclick = () => { $('regex-button').click(); toast('Build a pattern for the settings search, then type it into the settings field.'); }; }
mountLanguageControls();
function applyFunnyCopy() {
  const settings = JSON.parse(localStorage.getItem('dim-sum-language-settings') || '{"language":"en","funnyEn":"2","funnyYue":"2"}');
  const mode = settings.language || 'en';
  const enLevel = Number(settings.funnyEn || 2);
  const yueLevel = Number(settings.funnyYue || 2);
  const hero = document.querySelector('.hero-copy');
  if (!hero) return;
  const en = enLevel >= 4
    ? 'Browse the atlas, because every steamer basket deserves a proper introduction.'
    : enLevel >= 3
      ? 'Browse every dish with ingredients, allergens, and a little tea-house mischief.'
      : 'Browse every dish in the atlas, with ingredients, allergens, and fictional tea-house lore.';
  const yue = yueLevel >= 4
    ? '逐款睇點心，蒸籠入面每位選手都有自己嘅出場介紹㗎。'
    : yueLevel >= 3
      ? '逐款睇材料、過敏原，同埋少少茶樓笑料。'
      : '逐款睇材料、過敏原，同埋標明係虛構嘅茶樓故事。';
  hero.textContent = mode === 'yue' ? yue : mode === 'bilingual' ? `${en} · ${yue}` : en;
}
applyFunnyCopy();
document.querySelectorAll('#language-mode, #funny-en, #funny-yue').forEach(control => control.addEventListener('input', applyFunnyCopy));
mountNarratorControls();
mountSettingsSearch();
function bindHistory() { ['history-search','history-from','history-to'].forEach(id => $(id)?.addEventListener('input', renderHistory)); $('history-export')?.addEventListener('click', () => { if (!state.history.length) return toast('There is no history to export.'); const body = state.history.map(x => `${x.at}\t${x.action}\t${x.message}`).join('\n'); const blob = new Blob([body], {type:'text/plain'}); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'dim-sum-atlas-history.txt'; link.click(); recordHistory('export', 'Exported local history'); }); }
bindHistory();
function bindChangelog() { const card = document.querySelector('.changelog-entry'); if (!card) return; const apply = () => { const q = ($('changelog-search').value || '').toLowerCase(); const from = $('changelog-from').value; const to = $('changelog-to').value; const date = card.querySelector('small')?.textContent.match(/\d{4}-\d{2}-\d{2}/)?.[0] || ''; const ok = (!q || card.textContent.toLowerCase().includes(q)) && (!from || date >= from) && (!to || date <= to); card.hidden = !ok; $('changelog-empty').classList.toggle('hidden', ok); return ok; }; ['changelog-search','changelog-from','changelog-to'].forEach(id => $(id)?.addEventListener('input', apply)); $('changelog-export')?.addEventListener('click', () => { if (!apply()) return toast('There are no releases to export.'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`Dim Sum Atlas changelog export\n\n${card.textContent.trim()}\n`], {type:'text/plain'})); link.download = 'dim-sum-atlas-changelog.txt'; link.click(); toast('Exported filtered changelog.'); }); }
bindChangelog();
let narrationBusy = false; let narrationPending = '';
function narrate(message) { const setting = JSON.parse(localStorage.getItem('dim-sum-narrator') || '{}'); if (setting.enabled !== true || !('speechSynthesis' in window)) return; narrationPending = message; if (narrationBusy) return; const next = () => { if (!narrationPending) { narrationBusy = false; return; } narrationBusy = true; const text = narrationPending; narrationPending = ''; const langs = setting.language === 'both' ? ['en-US','yue-HK'] : [setting.language === 'yue' ? 'yue-HK' : 'en-US']; const lang = langs.shift(); const u = new SpeechSynthesisUtterance(text); u.lang = lang; u.onend = () => { if (langs.length) { const second = new SpeechSynthesisUtterance(text); second.lang = langs[0]; second.onend = () => { narrationBusy = false; next(); }; window.speechSynthesis.speak(second); } else { narrationBusy = false; next(); } }; u.onerror = u.onend; window.speechSynthesis.speak(u); }; next(); }
init().catch(err => { console.error(err); toast('The local catalog could not be loaded.'); });
