const state = { catalog: [], filtered: [], selected: null, category: 'All', query: '', selectedIds: new Set(), favorites: new Set(JSON.parse(localStorage.getItem('dim-sum-favorites') || '[]')) };
const $ = (id) => document.getElementById(id);
const lore = (dish) => ({ origin: `A fictional tea-house note imagines ${dish.name.en} taking shape in a bustling Kowloon kitchen where the first basket was counted by the rhythm of the kettle.`, facts: [`Fictional catalog fact: its best-known table companion is a cup of fragrant tea.`, `Fictional catalog fact: the name is said to be easiest to remember after the first bite.`, `Fictional catalog fact: cooks traditionally watch the steam, not the clock.`] });
function imageUrl(dish) { return dish.image?.assetUrl || ''; }
async function hydrateImage(image, dish) { if (!image || image.src || !dish.image?.releaseUrl) return; try { image.src = await window.atlas.ensureImage({ releaseUrl: dish.image.releaseUrl, relativePath: dish.image.path }); } catch { image.classList.add('image-unavailable'); image.alt = `${dish.name.en}, image unavailable in the catalog release`; } }
function dishText(d) { return [d.name?.en, d.name?.zhHant, d.description?.en, d.description?.yue, d.category, d.subcategory, ...(d.ingredients || []), ...(d.allergens || [])].join(' ').toLowerCase(); }
function renderChips() { const categories = ['All', ...new Set(state.catalog.map(d => d.category).filter(Boolean))].slice(0, 9); $('category-chips').innerHTML = categories.map(c => `<button class="chip ${c === state.category ? 'active' : ''}" data-category="${c}">${c.replaceAll('-', ' ')}</button>`).join(''); document.querySelectorAll('[data-category]').forEach(b => b.onclick = () => { state.category = b.dataset.category; apply(); }); }
function apply() { state.filtered = state.catalog.filter(d => (state.category === 'All' || d.category === state.category) && (!state.query || dishText(d).includes(state.query.toLowerCase()))); renderGallery($('gallery'), state.filtered); $('dish-count').textContent = state.catalog.length.toLocaleString(); $('hero-total').textContent = state.catalog.length.toLocaleString(); $('favorite-count').textContent = state.favorites.size; }
function renderGallery(target, dishes) { target.innerHTML = dishes.slice(0, 120).map(d => `<button class="card" data-id="${d.id}"><img loading="lazy" src="${imageUrl(d)}" alt="${d.image?.alt?.en || d.name.en}" /><div class="card-copy"><h3>${d.name.en}</h3><p>${d.name.zhHant || ''}</p><div class="card-meta"><span>${(d.category || 'dish').replaceAll('-', ' ')}</span><span>${state.selectedIds.has(d.id) ? '✓ Selected' : state.favorites.has(d.id) ? '♥' : '♡'}</span></div></div></button>`).join('') || '<p class="hero-copy">No dishes match this search.</p>'; target.querySelectorAll('[data-id]').forEach(b => { const dish = state.catalog.find(d => d.id === b.dataset.id); hydrateImage(b.querySelector('img'), dish); b.onclick = (event) => { if (event.shiftKey || event.ctrlKey) { toggleSelection(b.dataset.id); } else select(b.dataset.id); }; }); }
function toggleSelection(id) { state.selectedIds.has(id) ? state.selectedIds.delete(id) : state.selectedIds.add(id); $('selection-count').textContent = state.selectedIds.size; apply(); }
async function exportSelected() { const records = state.catalog.filter(d => state.selectedIds.has(d.id)); if (!records.length) return toast('Select at least one image first.'); const imagesOnly = confirm('Export the selected local images and a manifest? Choose Cancel for metadata only.'); const format = imagesOnly ? 'json' : prompt('Format: json, csv, markdown, txt, or html', 'json'); if (!['json','csv','markdown','txt','html'].includes(format)) return toast('Choose a supported export format.'); const archive = prompt('Archive: blank, zip, or 7z', '7z'); const password = archive === '7z' ? prompt('Optional 7z password, leave blank for none', '') : ''; try { const result = await window.atlas.exportRecords({ records, format, archive: archive || null, password, imagesOnly }); if (!result.canceled) toast(`Exported ${records.length} selected images to ${result.archive || result.format}.`); } catch (error) { toast(error.message); } }
function select(id) { const d = state.catalog.find(x => x.id === id); if (!d) return; state.selected = d; const fiction = lore(d); $('detail').innerHTML = `<img src="${imageUrl(d)}" alt="${d.image?.alt?.en || d.name.en}" /><div class="detail-body"><p class="eyebrow">${(d.category || 'dish').replaceAll('-', ' ')}</p><h2>${d.name.en}</h2><p class="subtitle">${d.name.zhHant || ''} · ${d.jyutping || ''}</p><p>${d.description?.en || 'A catalogued dim-sum dish with a story waiting to be tasted.'}</p><p class="detail-label">Fictional origin lore</p><p>${fiction.origin}</p><p class="detail-label">Fictional catalog facts</p><ul>${fiction.facts.map(f => `<li>${f}</li>`).join('')}</ul><p class="detail-label">Ingredients</p><div class="tag-row">${(d.ingredients || []).map(x => `<span class="tag">${x}</span>`).join('')}</div><p class="detail-label">Allergens</p><div class="tag-row">${(d.allergens || []).map(x => `<span class="tag">${x}</span>`).join('') || '<span class="tag">None listed</span>'}</div><button class="filter-button" style="margin-top:22px" id="favorite-detail">${state.favorites.has(d.id) ? '♥ Saved' : '♡ Save dish'}</button></div>`; $('favorite-detail').onclick = () => toggleFavorite(d.id); }
function toggleFavorite(id) { state.favorites.has(id) ? state.favorites.delete(id) : state.favorites.add(id); localStorage.setItem('dim-sum-favorites', JSON.stringify([...state.favorites])); apply(); if (state.selected?.id === id) select(id); }
function bindTabs() { document.querySelectorAll('.tab').forEach(t => t.onclick = () => { document.querySelectorAll('.tab').forEach(x => { x.classList.remove('active'); x.setAttribute('aria-selected', 'false'); }); t.classList.add('active'); t.setAttribute('aria-selected', 'true'); document.querySelectorAll('.panel').forEach(p => p.classList.add('hidden')); $(`${t.dataset.tab}-panel`).classList.remove('hidden'); if (t.dataset.tab === 'favorites') renderGallery($('favorites-gallery'), state.catalog.filter(d => state.favorites.has(d.id))); }); }
async function init() { const data = await window.atlas.readCatalog(); state.catalog = data.dishes || []; renderChips(); apply(); bindTabs(); $('search').oninput = e => { state.query = e.target.value; apply(); }; $('regex-button').onclick = () => toast('Regex builder is coming beside this search field.'); $('settings-button').onclick = () => toast('Appearance and language settings are next in the build.'); $('export-button').onclick = exportSelected; $('bulk-export').onclick = exportSelected; $('select-visible').onclick = () => { state.filtered.slice(0, 120).forEach(d => state.selectedIds.add(d.id)); $('selection-count').textContent = state.selectedIds.size; apply(); }; $('clear-selection').onclick = () => { state.selectedIds.clear(); $('selection-count').textContent = '0'; apply(); }; }
function toast(message) { $('toast').textContent = message; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2800); }
init().catch(err => { console.error(err); toast('The local catalog could not be loaded.'); });
